'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7M5 9v11h5v-6h4v6h5V9',book:'M12 6c-3-3-7-3-10-1v15c3-2 7-2 10 1 3-3 7-3 10-1V5c-3-2-7-2-10 1Zm0 0v15',cards:'m6 3 14 2-2 16L4 19 6 3ZM8 8h8M8 12h6',chat:'M21 11a9 8 0 0 1-9 8H7l-5 3 1-7a8 8 0 0 1 9-12 9 8 0 0 1 9 8ZM8 10h8M8 14h5',grammar:'M4 5h16M8 3v2M6 9c2 6 6 8 9 9M16 5c-1 8-6 13-12 15m12-7 4 8m-6-2h7',chart:'M4 3v18h17M8 16v-4m5 4V7m5 9v-6',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z',calendar:'M4 5h16v16H4V5ZM8 3v4m8-4v4M4 10h16M8 14h2m4 0h2m-8 3h2',settings:'M9 3h6l1 4 4 2v6l-4 2-1 4H9l-1-4-4-2V9l4-2 1-4Zm6 9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',arrow:'M4 12h16m-6-6 6 6-6 6',chevron:'m9 6 6 6-6 6',headphones:'M4 14v-3a8 8 0 0 1 16 0v3M4 12H2v7h5v-7H4Zm16 0h2v7h-5v-7h3Z',sound:'M10 5 5 9H2v6h3l5 4V5Zm4 3a5 5 0 0 1 0 8m3-11a9 9 0 0 1 0 14',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7ZM21 2v4m-2-2h4',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',leaf:'M20 3C8 2 2 9 5 16s15 2 15-13ZM4 21 15 10',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8',check:'m5 12 4 4L19 6',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',coffee:'M4 7h12v9a5 5 0 0 1-10 0L4 7Zm12 0h2a3 3 0 0 1 0 6h-2M3 22h16M7 2v2m5-2v2',train:'M5 4h14v14H5V4Zm0 8h14M9 4v8m-1 9-3 2m11-2 3 2M8 16h1m6 0h1',store:'M3 9h18l-3-6H6L3 9ZM5 9v12h14V9M9 21v-7h6v7',smile:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM8 14q4 5 8 0M8 9h.1m7.9 0h.1',stop:'M6 6h12v12H6Z',play:'m7 4 14 8-14 8V4Z',folder:'M3 5h7l2 3h9v13H3V5Z',refresh:'M3 11a9 9 0 0 1 15-7l3 3M21 2v5h-5M21 13a9 9 0 0 1-15 7l-3-3m0 5v-5h5'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.spark}"/></svg>`;
const navItems=[['home','home','今日学习'],['lessons','book','每日课程'],['grammar_library','book','语法学习'],['jlpt','calendar','JLPT 真题'],['cards','cards','即时学习卡'],['chat','chat','真实对话'],['grammar','grammar','语法解码器'],['immersion','globe','沉浸日语'],['progress','chart','学习进度']];
const scenes=[['cafe','coffee','街角咖啡店','礼貌点单，练习请求'],['meet','smile','初次见面','问好与自我介绍'],['station','train','在车站问路','询问方向与时间'],['store','store','便利店购物','选择商品与结账']];
let state, page='home', lesson=null, test=null, cardList=[], cardIndex=0, flipped=false, selectedCard=null, cardSearch='', generatingCard=false, randomCount=5, generatedIds=[], scene='cafe', decoded=null, story=null, record=false, busyCount=0, lastExport=null, catalog=null, checkpoint=null;
let selectedLessonNo=null, lessonLoading=false, lessonLoadError='', lessonRequest=0, stageRequest=0;
let navigationRun=0,cardLoadRun=0,progressLoadRun=0,refreshRun=0;
const generatingLessons=new Set();
let aiConfig=null;
let dailyWord=null, dailyWordLoading=false, dailyWordError='', dailyWordAdded=false;
const drafts={chat:'',grammar:'わたしは中国人です。',word:'',topic:'街角的咖啡店'};
const pending=new Map();let reqId=0;
window.haruResolve=(id,result)=>{const p=pending.get(id);if(!p)return;clearTimeout(p.timer);pending.delete(id);result.ok?p.resolve(result.data):p.reject(new Error(result.error||'操作未完成'));};
function rpc(action,params={}){return new Promise((resolve,reject)=>{const id=++reqId;if(haruHasNative()){const timer=setTimeout(()=>{pending.delete(id);reject(new Error('操作超时，请稍后重试。'));},610000);pending.set(id,{resolve,reject,timer});haruPostMessage({id,action,params});}else if(location.protocol.startsWith('http')){fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,params})}).then(r=>r.json()).then(r=>r.ok?resolve(r.data):reject(new Error(r.error))).catch(()=>reject(new Error('本地预览连接失败。')));}else reject(new Error('请通过 start.command（macOS）或 start.cmd（Windows）打开应用。'));});}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.className='show'+(error?' error':'');clearTimeout(t.timer);t.timer=setTimeout(()=>t.className='',error?7500:3500);}
async function run(label,fn,button){if(button?.disabled)return;busyCount++;$('#busy-label').textContent=label;$('#busy').hidden=false;if(button)button.disabled=true;try{return await fn();}catch(e){toast(e.message,true);}finally{if(button)button.disabled=false;busyCount--;if(!busyCount)$('#busy').hidden=true;}}
async function refresh(){const request=++refreshRun;const result=await rpc('bootstrap');if(request!==refreshRun)return state;state=result;if(!catalog||catalog.stage===state.progression.stage)catalog=state.curriculum;$('#profile-name').textContent=state.profile.name;document.body.classList.toggle('hide-romaji',!state.profile.romaji);return state;}
const btn=(text,action,cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;
const title=(name,sub,extra='')=>`<div class="page-title"><div><div class="eyebrow">YOUR JAPANESE JOURNEY</div><h1>${name}</h1><p>${sub}</p></div>${extra}</div>`;
const source=o=>`<div class="source"><span class="dot"></span>${esc(o.source||'')}${o.model?' · '+esc(o.model):''}<span>学习内容可随时对照官方资料核实</span></div>`;
const speak=(s,small=false)=>`<button class="${small?'btn small':'icon-btn'}" data-speak="${esc(s)}" title="日语朗读" aria-label="日语朗读">${icon('sound')}${small?' 听一听':''}</button>`;
const ex=x=>`<div class="example"><div><p class="jp" lang="ja">${japanese(x.jp)}</p><p class="reading">${esc(x.kana)} <span class="romaji">· ${esc(x.romaji)}</span></p><p class="translation">${esc(x.zh)}</p></div>${speak(x.jp)}</div>`;
const empty=(name,desc,action='')=>`<div class="empty">${icon('leaf')}<h3>${name}</h3><p>${desc}</p>${action}</div>`;
function nav(){return navItems.map(([id,i,t])=>`<button class="nav-item ${page===id?'active':''}" data-nav="${id}">${icon(i)}${t}${id==='cards'&&state?.stats.due?`<span class="nav-count">${state.stats.due}</span>`:''}</button>`).join('');}
async function navigate(to){if(!navItems.some(n=>n[0]===to)&&to!=='settings')to='home';const request=++navigationRun;page=to;if(to==='settings')aiConfig=null;if(to!=='cards')cardLoadRun++;if(to!=='progress')progressLoadRun++;$('#nav').innerHTML=nav();$('#settings-nav').classList.toggle('active',page==='settings');$('#page-crumb').textContent=navItems.find(n=>n[0]===to)?.[2]||'偏好设置';render();window.scrollTo(0,0);if(to==='settings')await loadAIConfig();if(to==='lessons'&&selectedLessonNo===null&&!lesson&&!checkpoint)await openLesson(state.progression.next_lesson||catalog.courses[0].lesson_no);if(to==='cards'){const read=++cardLoadRun;await run('正在打开你的卡片…',async()=>{const result=await rpc('cards',{order:'recent'});if(request!==navigationRun||read!==cardLoadRun||page!=='cards')return;cardList=result;cardIndex=0;flipped=false;selectedCard=null;render();});}if(to==='grammar_library'||to==='jlpt')await loadStudy(to);if(to==='chat')await loadChat();if(to==='progress'){const read=++progressLoadRun;await refresh();if(request===navigationRun&&read===progressLoadRun&&page==='progress')render();}}
function render(){if(!state)return;const f={home:homeView,lessons:lessonsView,cards:cardsView,chat:chatView,grammar:grammarView,grammar_library:grammarLibraryView,jlpt:jlptView,progress:progressView,immersion:immersionView,settings:settingsView};$('#main').innerHTML=f[page]();enhanceLearning();syncCourseSelection();}
function dailyWordView(){
 const header='<div class="card-title"><h3>今日的一点日语</h3><span>DAILY WORD</span></div>';
 if(dailyWordLoading)return header+'<p class="word-meaning" role="status">AI 正在准备这次的一点日语…</p>';
 if(dailyWordError)return header+`<p class="word-meaning" role="alert">${esc(dailyWordError)}</p><div class="word-foot">${btn('重新生成','retry-daily-word','small')}</div>`;
 if(!dailyWord)return header;
 return header+`<div class="word-kana" lang="ja">${esc(dailyWord.word)}</div><div class="word-romaji" lang="ja">${esc(dailyWord.reading)}</div><div class="word-romaji romaji">${esc(dailyWord.romaji)}</div><div class="word-meaning">${esc(dailyWord.meaning)}</div><div class="word-foot">${speak(dailyWord.word,true)}<button class="text-link" data-action="add-daily-word" ${dailyWordAdded?'disabled':''}>${dailyWordAdded?'已加入词卡':'＋ 加入词卡'}</button></div><p class="hint">AI 生成 · ${esc(dailyWord.model)}</p>`;
}
function renderDailyWord(){const card=$('#daily-word');if(card)card.innerHTML=dailyWordView();}
async function loadDailyWord(){
 if(dailyWordLoading)return;
 dailyWordLoading=true;dailyWordError='';renderDailyWord();
 try{dailyWord=await rpc('daily_word');dailyWordAdded=false;}
 catch(e){dailyWordError=e.message;}
 finally{dailyWordLoading=false;renderDailyWord();}
}
function homeView(){const s=state.stats;const next=s.next_day;const progress=state.progression;const dateText=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});return title(`你好，${esc(state.profile.name)} <span style="font-size:26px">☀</span>`,'让日语一点一点，走进你的日常。',`<div class="date-pill">${icon('calendar')}${dateText}</div>`)+`<div class="home-grid"><div><section class="hero"><div class="hero-content"><span class="pill">✦ 你的日语旅程，从这里开始</span><h2>每天一点点，<br>离日本更近一点。</h2><p>不必一下子学会所有。今天，<br>从一句简单的问候开始吧。</p>${btn((progress.next_lesson?'继续第 '+progress.next_lesson+' 课':'继续阶段学习')+' '+icon('arrow'),'start-lesson','rose')}</div><img class="hero-art" src="garden.svg" alt="樱花、富士山与窗边的一杯茶"></section>${stagePanel()}<div class="section-heading"><h2>今天，学点什么 <span>DAILY LESSON</span></h2><button class="text-link" data-nav="lessons">课程一览 ${icon('chevron')}</button></div><div class="lesson-preview">${[['grammar','book','blue','一点语法',progress.next_focus,'理解句子'],['speaking','chat','','开口说日语','跟着例句，勇敢说出第一句','跟读练习'],['listening','headphones','peach','让耳朵熟悉日语','听一听，感受日语的节奏','听力练习']].map(([tab,i,c,t,d,b])=>`<button class="mini-lesson" data-action="start-lesson" data-tab="${tab}"><span class="tile-icon ${c}">${icon(i)}</span><h3>${t}</h3><p>${esc(d)}</p><div class="tile-bottom"><span>${b}</span><b>开始 →</b></div></button>`).join('')}</div><div class="section-heading"><h2>换一种方式，亲近日语 <span>EXPLORE</span></h2></div><div class="tool-grid">${[['cards','cards','','把单词变成记忆','例句、记忆技巧与间隔复习'],['chat','coffee','peach','去咖啡店聊两句','AI 陪你练习真实生活对话'],['grammar','grammar','blue','拆开一句日语','看懂助词、词序和句子结构'],['immersion','globe','green','走进日语的日常','从一个短故事开始沉浸']].map(([n,i,c,t,d])=>`<button class="tool-card" data-nav="${n}"><span class="tile-icon ${c}">${icon(i)}</span><div><h3>${t}</h3><p>${d}</p></div>${icon('chevron')}</button>`).join('')}</div></div><aside class="right-rail"><section class="card progress-card"><div class="card-title"><h3>小小积累，也有力量</h3>${icon('chart')}</div><div class="progress-ring"><strong>${progress.completed}<i style="font-size:16px;font-style:normal;color:var(--muted)"> / ${progress.total}</i></strong><small>阶段 ${progress.stage} · 已完成</small></div><div class="stats-row"><div><strong>${s.streak}<i> 天</i></strong><small>连续学习</small></div><div><strong>${s.cards}<i> 个</i></strong><small>已收集单词</small></div><div><strong>${s.due}<i> 张</i></strong><small>待复习卡片</small></div></div><div class="week-days">${s.activity.map((d,i)=>`<div class="week-day ${d.count?'done':''} ${i===6?'today':''}">${new Date(d.date+'T12:00:00').toLocaleDateString('zh-CN',{weekday:'narrow'})}<div>${d.count?'✓':i===6?'·':'–'}</div></div>`).join('')}</div></section><section class="card word-card" id="daily-word" aria-live="polite">${dailyWordView()}</section><div class="tip-note"><strong>✧ 给刚开始的你</strong>会认汉字，是你的优势。<br>先听声音，再看文字，让日语有自己的记忆。</div></aside></div>`;}
function stagePanel(){const p=state.progression;const status={learning:'继续课程',assessment_due:'可以开始阶段评估',review_required:'先补强，再评估',reassessment_ready:'补强已完成，可以重新评估'}[p.status];return `<section class="card stage-panel"><div class="card-title"><h3>第 ${p.stage} 阶段 · ${esc(p.name)}</h3><span>${p.completed} / ${p.total} 课</span></div><p class="hint">第 ${p.start}–${p.end} 课 · ${status} · 累计完成 ${p.completed_total} 课</p><div class="bar"><i style="width:${p.completed/p.total*100}%"></i></div><p class="hint">${esc(p.pass_rule)}</p><div class="form-row">${btn(p.next_lesson?'继续第 '+p.next_lesson+' 课':p.status==='review_required'?'打开错题补强':p.status==='reassessment_ready'?'重新阶段评估':'开始阶段评估','start-lesson','soft')}</div></section>`;}
function lessonsView(){return title('每日课程','从五十音出发，把语法、口语和听力放进每一天。')+stagePanel()+`<div class="panel-grid"><div class="stack">${lessonSelection()}<div class="card lesson-body" id="lesson-body">${checkpoint?`<h2>${esc(checkpoint.title)}</h2><p class="hint">从本阶段 ${checkpoint.coverage} 节已学课抽取 ${checkpoint.questions.length} 题。${esc(checkpoint.rule)}</p>${quizHTML(checkpoint,'stage_assessment')}${source(checkpoint)}`:lesson?lessonBody():pendingLesson()}</div></div><aside class="stack" style="align-content:start"><div class="card"><h3>五十音 · 随手听一听</h3><p class="hint">平假名 / 片假名 · 点击朗读<br>下表为基础清音，留空位置不是缺失。</p><div class="kana-grid">${state.kana.flat().map(([h,k,r])=>h?`<button class="kana-cell" data-speak="${h}"><b>${h}</b><span>${k}</span><small class="romaji">${r}</small></button>`:'<div></div>').join('')}</div></div><div class="card history-list"><h3>最近打开的课程</h3>${state.recent.filter(l=>l.source==='AI生成').map(l=>`<button data-action="select-lesson" data-day="${l.lesson_no||l.day}">第 ${l.lesson_no||l.day} 课 · ${esc(l.title)}</button>`).join('')||'<p class="hint">完成第一步后，会在这里留下足迹。</p>'}</div></aside></div>`;}
function syncCourseSelection(){
 const list=$('.course-list'),active=list?.querySelector('[aria-pressed="true"]');
 if(!active)return;
 const box=list.getBoundingClientRect(),item=active.getBoundingClientRect();
 if(item.top<box.top)list.scrollTop-=box.top-item.top;
 else if(item.bottom>box.bottom)list.scrollTop+=item.bottom-box.bottom;
}
function lessonSelection(){
 const selected=catalog.courses.find(c=>c.lesson_no===selectedLessonNo);
 return `<div class="card course-selector"><label class="hint" for="lesson-stage">查看已解锁阶段</label><select id="lesson-stage">${state.stages.map(p=>`<option value="${p.stage}" ${p.stage===catalog.stage?'selected':''}>第 ${p.stage} 阶段 · ${esc(p.name)}</option>`).join('')}</select><p class="hint">按内置大纲选择课程。点击即可查看已生成内容，未生成的课程请先使用 AI 创建。</p><div class="course-list" role="group" aria-label="课程列表">${catalog.courses.map(c=>`<button class="course-choice ${c.lesson_no===selectedLessonNo?'selected':''}" data-action="select-lesson" data-day="${c.lesson_no}" aria-pressed="${c.lesson_no===selectedLessonNo}"><strong>第 ${c.lesson_no} 课 · ${esc(c.title)}</strong><span>${c.completed?'已完成 · ':''}${generatingLessons.has(c.lesson_no)?'正在生成':c.generated?'已生成':'待 AI 生成'}</span></button>`).join('')}</div>${selected?`<div class="form-row course-actions"><strong>第 ${selected.lesson_no} 课 · ${esc(selected.title)}</strong>${btn(icon('spark')+' AI 创建课程','generate-lesson','primary',generatingLessons.has(selectedLessonNo)?'disabled':'')}</div>${selected.generated?`<details><summary class="hint">需要不同的例句或练习？</summary><p class="hint">重建会调用 AI；内容校验不通过时最多重试一次。新版本独立保存，旧课与成绩保留。</p>${btn('重建所选 AI 课','regenerate-lesson','soft',generatingLessons.has(selectedLessonNo)?'disabled':'')}</details>`:''}`:''}</div>`;
}
function pendingLesson(){
 const selected=catalog.courses.find(c=>c.lesson_no===selectedLessonNo);
 if(lessonLoading)return '<div class="empty" role="status">正在读取所选课程…</div>';
 if(lessonLoadError)return empty('课程暂时无法读取',esc(lessonLoadError),btn('重新读取','select-lesson','soft',`data-day="${selectedLessonNo}"`));
 if(!selected)return empty('选择一课，开始学习','点击上方课程列表查看课程。');
 return empty(`第 ${selected.lesson_no} 课 · ${esc(selected.title)}`,generatingLessons.has(selectedLessonNo)?'AI 正在生成这节课，请稍候…':'这节课尚未由 AI 生成。请点击上方“AI 创建课程”，生成后即可开始学习。');
}
function lessonBody(){
 const rich=lesson.design_version>=2;
 return `<span class="pill">${lesson.kind==='remedial'?'错题补强':'第 '+(lesson.lesson_no||lesson.day)+' 课'} · 第 ${lesson.stage||1} 阶段</span><h2 style="font-size:28px;margin-top:12px">${esc(lesson.title)}</h2><p class="section-intro">${esc(lesson.goal)}</p>
 ${rich?`<div class="lesson-roadmap"><strong>这一课，你将能够</strong><ol>${lesson.objectives.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="hint">${lesson.sections.length} 节讲解 · ${lesson.vocabulary.length} 个词语 · ${lesson.examples.length} 个例句 · 情境对话 · ${lesson.production.length} 个表达任务 · ${lesson.questions.length} 道练习<br>时间较少时可分两次学习：先理解与听读，再脱稿表达与答题。</p></div>`:lesson.kind==='lesson'?'<p class="callout">这是已保存的简版课程。可通过上方“重建所选 AI 课”生成丰富版本，旧课与成绩会保留。</p>':''}
 <div class="tabs"><button class="tab active" data-lesson-tab="grammar">语法与例句</button><button class="tab" data-lesson-tab="speaking">口语与听力</button><button class="tab" data-lesson-tab="exercise">课后练习</button></div><div id="lesson-tab-content">${lessonTab('grammar')}</div>${reviewCoverage(lesson)}${source(lesson)}`;
}
function lessonTab(tab){
 if(tab==='grammar')return `<div class="block-title">${icon('book')}${lesson.sections?'先建立框架':'今天的一个知识点'}</div><div class="prose">${esc(lesson.grammar)}</div>
 ${(lesson.sections||[]).map((s,i)=>`<section class="block lesson-section"><h3>${i+1}. ${esc(s.title)}</h3><p class="prose">${esc(s.explanation)}</p></section>`).join('')}
 <div class="callout">给中文母语者的提示 · ${esc(lesson.tip)}</div>
 ${lesson.vocabulary?`<section class="block"><div class="block-title">${icon('cards')}本课词汇 · 先听读，再进入句子</div><div class="lesson-vocabulary">${lesson.vocabulary.map(v=>`<div class="lesson-word"><div class="card-title"><strong lang="ja">${esc(v.word)}</strong>${speak(v.word,true)}</div><div class="reading">${esc(v.reading)} <span class="romaji">· ${esc(v.romaji)}</span></div><p class="translation">${esc(v.meaning)}</p></div>`).join('')}</div></section>`:''}
 <div class="block"><div class="block-title">${icon('chat')}放进句子里，读一读</div>${lesson.examples.map(ex).join('')}</div>${btn('去练口语与听力 '+icon('arrow'),'to-speaking','soft','style="margin-top:20px"')}`;
 if(tab==='speaking')return `<div class="block-title">${icon('mic')}从跟读到自己表达</div><p class="prose">${esc(lesson.speaking)}</p>
 ${lesson.dialogue?`<section class="block lesson-dialogue"><h3>情境对话</h3><p class="hint">${esc(lesson.dialogue.scene)}</p>${lesson.dialogue.lines.map(x=>`<div class="dialogue-turn"><span class="tag">${esc(x.speaker)}</span>${ex(x)}</div>`).join('')}</section>`:lesson.examples.map(ex).join('')}
 <div class="inline-actions">${btn(icon('mic')+' 录下我的跟读','record','','id="record-btn"')}${btn(icon('play')+' 回放录音','play-recording')}</div><p class="hint">录音只在本机保存。回放后对照原音；此版本不对发音打分。<span id="record-status"></span></p>
 <div class="block"><div class="block-title">${icon('headphones')}听读示范 · 先听再核对</div>${speak(lesson.listening.jp,true)}<details style="margin-top:13px"><summary class="hint">听完后，展开原文</summary>${ex(lesson.listening)}</details></div>
 ${lesson.production?`<section class="block"><h3>换个情境，自己说</h3><p class="hint">先脱稿表达，再核对参考。合理表达可能不止一种；这部分用于自查，不自动评分。</p>${lesson.production.map((p,i)=>`<article class="production-task"><h4>任务 ${i+1} · ${esc(p.situation)}</h4><p class="prose">${esc(p.task)}</p><ul class="hint">${p.checklist.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><details><summary>完成后查看一种参考表达</summary>${ex(p.sample)}</details></article>`).join('')}</section>`:''}
 ${btn('完成课后练习 '+icon('arrow'),'to-exercise','primary','style="margin-top:20px"')}`;
 return `${lesson.design_version>=2?'<p class="callout">用学过的知识完成新情境任务。听力测验使用独立材料，先完整听完再选择；提交后查看解析。</p>':''}${quizHTML(lesson,lesson.kind)}`;
}
function quizHTML(d,kind){return `<div class="block-title">${icon('leaf')}${{lesson:'巩固一下，再向前走',quiz:'只考本周学过的内容',stage_assessment:'阶段评估 · 仅首次提交生效',remedial:'错题补强 · 可以重新练习'}[kind]}</div><p class="hint">选择答案后提交，查看解析。${kind==='lesson'?'提交后记录本节课程已完成。':kind==='remedial'?'达到总正确率80%、各受测类别60%后，可开始新的阶段评估；补强不增加课次。':kind==='stage_assessment'?'总正确率至少80%，且各受测类别至少60%，才解锁下一阶段。题目是已学题抽样，不是考试认证。':''}</p><form id="quiz-form" data-id="${d.id}">${d.questions.map((q,i)=>`<div class="quiz-question"><h4>${i+1}. ${esc(q.prompt)}</h4>${q.audio?speak(q.audio,true):''}<div class="options" style="margin-top:10px">${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required>${esc(o)}</label>`).join('')}</div><div id="feedback-${i}"></div></div>`).join('')}<button class="btn primary" type="submit" style="margin-top:20px">提交答案 ${icon('check')}</button></form><div id="quiz-result"></div>`;}
function cardHistoryRows(){
 const query=cardSearch.normalize('NFKC').trim().toLocaleLowerCase();
 const cards=cardList.filter(c=>[c.word,c.reading,c.romaji,c.meaning].some(v=>String(v||'').normalize('NFKC').toLocaleLowerCase().includes(query)));
 return cards.map(c=>`<button class="word-row history-card ${selectedCard===c.id?'selected':''}" data-action="open-card" data-id="${esc(c.id)}" aria-label="查看词卡：${esc(c.word)}"><span><b lang="ja">${esc(c.word)}</b><small>${esc(c.meaning)}</small></span><span>${c.ready?'待复习':esc(c.due.slice(5,10)+' '+c.due.slice(11,16))}</span></button>`).join('')||`<p class="hint">${cardList.length?'没有找到匹配的词卡。':'还没有词卡。生成后会自动保存在这里。'}</p>`;
}
function cardAnswer(c){return `<div class="reading">${esc(c.reading)} <span class="romaji">· ${esc(c.romaji)}</span></div><div class="meaning">${esc(c.meaning)}</div><p class="jp" style="font-size:20px">${esc(c.example)}</p><p class="translation">${esc(c.translation)}</p><p class="hint">✧ ${esc(c.mnemonic)}</p>`;}
function cardsView(){
 const due=cardList.filter(c=>c.ready);const viewed=cardList.find(c=>c.id===selectedCard);const c=viewed||due[cardIndex%due.length];
 return title('即时学习卡','随机遇见新单词，也随时回看已经收好的词卡。')+`<div class="cards-layout"><div class="stack"><div class="card"><form id="card-form" class="form-row"><input id="card-word" aria-label="日语或中文单词" placeholder="输入一个单词，如：ありがとう / 咖啡" value="${esc(drafts.word)}" maxlength="100" required><button class="btn primary" ${generatingCard?'disabled':''}>${icon('spark')} 生成学习卡</button></form><div class="inline-actions"><label for="random-count" class="hint">生成数量</label><select id="random-count" aria-label="随机生成数量" ${generatingCard?'disabled':''}>${[1,5,10].map(n=>`<option value="${n}" ${randomCount===n?'selected':''}>${n} 张</option>`).join('')}</select>${btn(icon('refresh')+' 随机生成新词卡','random-card','soft',generatingCard?'disabled':'')}</div><p class="hint">随机生成会排除已有词条，重复时最多尝试三次。整批成功后保存到历史；生成需要 AI 连接。</p></div>
 ${generatedIds.length?`<section class="card"><h3>本次新增 ${generatedIds.length} 张</h3><div class="inline-actions">${generatedIds.map(id=>cardList.find(c=>c.id===id)).filter(Boolean).map(c=>btn(esc(c.word),'open-card','soft small',`data-id="${esc(c.id)}"`)).join('')}</div></section>`:''}
 <div class="card"><div class="card-title"><h3>${viewed?'单词卡详情':'今天的复习'}</h3><span>${due.length} 张到期 · 共 ${cardList.length} 张</span></div>
 ${c?`${viewed?`<div class="flashcard card-detail"><span class="eyebrow">YOUR WORD COLLECTION</span><div class="word" lang="ja">${esc(c.word)}</div>${cardAnswer(c)}</div><p class="hint">${c.created?'收录于 '+esc(c.created.replace('T',' ')):'历史词卡 · 收录时间未记录'} · ${c.ready?'已到期，可返回复习':'下次复习 '+esc(c.due.replace('T',' '))}</p>${btn('返回到期复习','card-review','soft')}`:`<button class="flashcard" data-action="flip"><span class="eyebrow">${flipped?'THE OTHER SIDE':'TAKE YOUR TIME'}</span><div class="word" lang="ja">${esc(c.word)}</div>${flipped?cardAnswer(c):'<p class="hint">在心里想一想，读音和意思是什么？</p>'}<span class="flip-hint">点击卡片${flipped?'返回正面':'翻看答案'}</span></button>`}<div class="inline-actions">${speak(c.word,true)}${speak(c.example,true)}</div>${!viewed&&flipped?`<div class="review-buttons">${[[1,'还没记住','10分钟后'],[3,'有些困难','按进度安排'],[4,'记住了','按进度安排'],[5,'很轻松','按进度安排']].map(([q,t,h])=>`<button data-action="review" data-quality="${q}" data-id="${c.id}">${t}<br><small>${h}</small></button>`).join('')}</div>`:''}${pronunciationHTML(c.pronunciation)}${source(c)}`:empty(cardList.length?'今天的卡片都复习好了':'给单词一个小小的家',cardList.length?'可以查看历史单词卡，或随机生成一个新词。':'输入单词、随机生成，或从五张入门卡开始。',!cardList.length?btn('加入五张入门卡','seed-cards','soft'):'')}</div></div>
 <section class="card cards-history" aria-labelledby="card-history-title"><div class="cards-history-header"><div><h2 id="card-history-title">历史单词卡 <span class="hint">${cardList.length} 张</span></h2><p class="hint">按收录时间从新到旧 · 点击查看完整内容<br>查看历史不会改变复习进度。</p></div><input id="card-search" aria-label="搜索历史单词卡" placeholder="搜索单词、读音或中文" value="${esc(cardSearch)}" maxlength="100"></div><div class="word-list" id="card-history">${cardHistoryRows()}</div></section><div class="tip-note"><strong>先回忆，再翻面</strong>努力想起单词的过程，本身就是学习。不认识也没关系，诚实评分就好。</div></div>`;
}
async function generateCard(word,button){
 if(generatingCard)return;
 const count=randomCount;
 generatingCard=true;
 try{await run(word?'正在制作你的学习卡…':'正在寻找未收录的新单词…',async()=>{
  if(page==='cards')render();
  let message;
  if(word){const previous=new Set(cardList.map(c=>c.id));await rpc('card_create',{word});cardList=await rpc('cards',{order:'recent'});const added=cardList.find(c=>!previous.has(c.id));selectedCard=added?.id||null;generatedIds=added?[added.id]:[];drafts.word='';message=added?'新词已收好，可在历史中随时查看。':'该词条已收录，可在历史中查看。';}
  else{const result=await rpc('card_random',{count});cardList=result.cards;generatedIds=result.generated.map(c=>c.id);selectedCard=generatedIds[0];cardSearch='';message='已收好 '+result.generated.length+' 张不重复的新词卡。';}
  flipped=false;await refresh();toast(message);
 },button);}finally{generatingCard=false;if(page==='cards')render();}
}

function grammarView(){return title('语法解码器','一句一句拆开，慢慢读懂日语的逻辑。')+`<div class="panel-grid"><div class="stack"><div class="card"><form id="decode-form"><textarea id="decode-input" placeholder="粘贴一句你想读懂的日语…" maxlength="1200" required>${esc(drafts.grammar)}</textarea><div class="form-row" style="margin-top:12px;justify-content:space-between"><span class="hint">成分分解 · 助词解释 · 中文母语者易错点</span><button class="btn primary">${icon('spark')} 解码这句话</button></div></form></div><div class="card">${decoded?`<p class="jp">${esc(decoded.sentence)}</p><p class="reading">${esc(decoded.reading)} <span class="romaji">· ${esc(decoded.romaji)}</span></p><p class="translation">${esc(decoded.translation)}</p><div class="token-row">${decoded.parts.map(x=>`<div class="token"><b>${esc(x.text)}</b><small>${esc(x.role)}</small></div>`).join('')}</div><p class="prose">${esc(decoded.structure)}</p>${decoded.parts.map(x=>`<div class="breakdown-row"><div>${esc(x.text)}<small class="muted" style="display:block">${esc(x.reading)}</small></div><span>${esc(x.role)}</span><p>${esc(x.explanation)}</p></div>`).join('')}<div class="callout">${esc(decoded.pitfall)}</div><h3 style="margin-top:20px">换个例子，再理解一次</h3>${decoded.examples.map(ex).join('')}${source(decoded)}`:empty('让句子变得透明','输入日语句子，Haru 会解释每一块在做什么，以及和中文表达的不同。')}</div></div><aside class="stack" style="align-content:start"><div class="card"><h3>从这些句子试试</h3><div class="history-list">${['わたしは中国人です。','水をください。','猫が好きです。','これは何ですか。'].map(s=>`<button data-example="${esc(s)}">${s}</button>`).join('')}</div></div><div class="tip-note"><strong>一个小提醒</strong>助词像句子里的路标。同一个词，换了助词，也可能走向不同的意思。</div></aside></div>`;}
function progressView(){const s=state.stats;return title('看见自己的进步','每一次开口、每一次想起，都算数。')+stagePanel()+`<div class="metrics"><div class="metric"><strong>${s.lessons}</strong><p>已完成课程 · 以提交练习为准</p></div><div class="metric"><strong>${s.streak} <small>天</small></strong><p>连续学习 · 课程 / 复习 / 对话</p></div><div class="metric"><strong>${s.attempts}</strong><p>已提交测验 · 同一份仅计一次</p></div></div><div class="panel-grid"><div class="stack"><div class="card"><h3>本周学习，小小验收</h3><p class="section-intro">周一至今，依据实际完成课程和已复习单词出题。分数来自已作答题目，不代表 JLPT 等级。</p><div class="form-row">${btn(icon('spark')+' AI 生成周测','weekly-quiz','primary')}${btn('从已学课程抽题','local-quiz')}</div></div><div class="card" id="weekly-quiz">${test?`<h2>${esc(test.title)}</h2><p class="hint">范围：${esc(test.scope.join('、'))}</p>${quizHTML(test,'quiz')}${source(test)}`:empty('了解你已经会了什么','先完成一节课，再来做本周测验。题目根据真实学习记录生成。')}</div></div><aside class="stack" style="align-content:start"><div class="card"><h3>练习表现</h3><p class="hint">课程、周测与阶段评估保留首次成绩；补强取最近一次成绩。</p>${Object.entries(s.skills).map(([k,v])=>`<div class="skill-row"><div><span>${{grammar:'语法与词汇',kana:'假名辨认',listening:'听力理解'}[k]}</span><span>${v.total?Math.round(v.correct/v.total*100)+'% · '+v.total+'题':'暂无记录'}</span></div><div class="bar"><i style="width:${v.total?v.correct/v.total*100:0}%"></i></div></div>`).join('')}</div><div class="card"><h3>值得再看一眼</h3>${state.mistakes.slice(0,4).map(m=>`<div class="callout"><b>${esc(m.prompt)}</b><br>${esc(m.explanation)}</div>`).join('')||'<p class="hint">暂时没有错题记录。错题会成为下一课的复习线索。</p>'}</div></aside></div>`;}
function immersionView(){return title('沉浸日语','用简单的日语，遇见有意思的日常。')+`<div class="panel-grid"><div class="stack"><div class="card"><form class="form-row" id="immersion-form"><input id="immersion-topic" placeholder="今天想走进什么场景？" value="${esc(drafts.topic)}" maxlength="100" required><button class="btn primary">${icon('spark')} 生成微故事</button></form><p class="hint">先读日语，听一遍，再按需展开中文。每次只接触一点新词。</p></div><div class="card">${story?`<div class="immersion-cover"><span class="eyebrow">A LITTLE EVERYDAY STORY</span><h2>${esc(story.title)}</h2><p>读一读 · 听一听 · 想象你就在这里</p></div>${speak(story.sentences.map(s=>s.jp).join(''),true)}${story.sentences.map(s=>`<div class="story-line"><div class="form-row" style="justify-content:space-between"><p class="jp" lang="ja">${japanese(s.jp)}</p>${speak(s.jp)}</div><details><summary>读音与中文提示</summary><p class="reading">${esc(s.kana)} <span class="romaji">· ${esc(s.romaji)}</span></p><p class="translation">${esc(s.zh)}</p></details></div>`).join('')}<div class="callout">今天的小任务 · ${esc(story.task)}</div>${reviewCoverage(story)}${source(story)}`:empty('让日语成为风景','一间咖啡店、一只猫、一次散步……告诉 Haru 你感兴趣的主题，创建你的入门微故事。')}</div></div><aside class="stack" style="align-content:start"><div class="card"><h3>故事里的小词典</h3>${story?story.words.map(w=>`<div class="word-row"><div><b>${esc(w.word)}</b><br><small>${esc(w.reading)} · ${esc(w.meaning)}</small></div><button class="icon-btn" data-add-word="${esc(w.word)}" title="生成学习卡">＋</button></div>`).join(''):'<p class="hint">生词会出现在这里，点击 + 即可用 AI 生成卡片。</p>'}</div><div class="tip-note"><strong>无需读懂每一个字</strong>先抓住大意，再借助读音和中文提示。让好奇心带着你往前走。</div></aside></div>`;}
function aiConfigView(){
 if(!aiConfig)return '<h3>AI 连接</h3><p class="hint" role="status">正在读取配置…</p>';
 const c=aiConfig;
 return `<h3>AI 连接</h3><p class="hint">保存到项目 .env，后续 AI 请求自动使用。密钥不会回显；留空保留原密钥。</p>
 ${c.overrides.length?`<p class="callout">当前启动环境中的 ${c.overrides.map(esc).join('、')} 优先于 .env。表单显示当前生效值；保存后仍受这些环境变量覆盖，需移除对应环境变量并重开 App 才能使用文件中的值。</p>`:''}
 <form id="ai-config-form" autocomplete="off"><fieldset class="ai-config-fields">
 <label>API 地址<input name="base" type="url" value="${esc(c.base)}" placeholder="https://api.example.com/v1" maxlength="2048" spellcheck="false" required></label>
 <label>API 密钥<input name="key" type="password" value="" placeholder="${c.key_configured?'已配置 · 留空保留原密钥':'填写你的 API 密钥'}" maxlength="4096" autocomplete="new-password" spellcheck="false" ${c.key_configured?'':'required'}></label>
 <div class="field-grid"><label>模型 ID<input name="model" value="${esc(c.model)}" placeholder="服务商提供的模型 ID" maxlength="200" spellcheck="false" required></label><label>超时时间（秒）<input name="timeout" type="number" value="${c.timeout}" min="10" max="90" step="any" required></label></div>
 <p class="hint">接口需兼容 Chat Completions；地址使用 HTTPS。测试连接会先保存，再发送一次 API 请求。</p>
 <div class="inline-actions"><button class="btn primary" type="submit" value="save">保存配置 ${icon('check')}</button><button class="btn soft" type="submit" value="test">保存并测试连接</button><button class="btn" type="button" data-action="refresh-config">${icon('refresh')} 刷新配置</button></div>
 </fieldset><p class="hint" id="ping-result" role="status" aria-live="polite"></p></form>`;
}
async function loadAIConfig(){
 const target=$('#ai-settings');
 await run('正在读取 AI 配置…',async()=>{
  try{const c=await rpc('config_get');if(target?.isConnected){aiConfig=c;target.innerHTML=aiConfigView();}}
  catch(e){if(target?.isConnected)target.innerHTML='<h3>AI 连接</h3><p class="hint" role="alert">'+esc(e.message)+'</p>'+btn('重新读取','refresh-config');throw e;}
 });
}
async function saveAIConfig(form,testConnection){
 const fields=form.querySelector('fieldset');if(fields.disabled)return;
 const data=new FormData(form),result=form.querySelector('#ping-result');
 const params={base:data.get('base'),model:data.get('model'),key:data.get('key'),timeout:Number(data.get('timeout'))};
 fields.disabled=true;result.textContent='正在保存配置…';let saved=false;
 await run(testConnection?'正在保存并测试 AI 连接…':'正在保存 AI 配置…',async()=>{
  try{
   const c=await rpc('config_save',params);saved=true;
   form.elements.key.value='';form.elements.key.required=!c.key_configured;form.elements.key.placeholder=c.key_configured?'已配置 · 留空保留原密钥':'填写你的 API 密钥';
   if(form.isConnected)aiConfig=c;
   result.textContent=c.overrides.length?'已保存到 .env；当前仍优先使用启动环境变量。':'已保存到 .env，后续请求自动使用。';
   if(testConnection){result.textContent+=' 正在测试连接…';const r=await rpc('ping');result.textContent='配置已保存，连接成功 · 实际返回模型：'+r.model;}
  }catch(e){result.textContent=(saved?'配置已保存；测试连接失败：':'配置未保存：')+e.message;throw e;}
  finally{fields.disabled=false;params.key='';}
 });
}
function settingsView(){const p=state.profile;return title('学习偏好','找到舒服的节奏，让学习自然发生。')+`<div class="panel-grid"><div class="stack"><div class="card"><form id="profile-form"><div class="field-grid"><label>怎么称呼你<input name="name" value="${esc(p.name)}" maxlength="30" required></label><label>每天学习时长（分钟）<input name="minutes" type="number" value="${p.minutes}" min="5" max="90" required></label><label>学习目标<select name="goal">${['日常交流','旅行日语','兴趣与文化','打好基础，再准备JLPT'].map(g=>`<option ${p.goal===g?'selected':''}>${g}</option>`).join('')}</select></label></div><label class="check-label" style="margin:20px 0"><input type="checkbox" name="romaji" ${p.romaji?'checked':''}>显示辅助罗马音（熟悉假名后可以关闭）</label><button class="btn primary">保存偏好 ${icon('check')}</button></form></div><div class="card" id="ai-settings">${aiConfigView()}</div></div><aside class="stack" style="align-content:start"><div class="card"><h3>你的学习记录</h3><p class="hint">课程、卡片、对话和测验保存于本机 SQLite 数据库。导出包含个人学习内容，请妥善保存。</p>${btn(icon('download')+' 导出学习档案','export-json','soft','style="margin-top:15px"')}</div><div class="tip-note"><strong>关于隐私与声音</strong>点击 AI 功能后，相关输入、近期学习摘要与错题会发送到你配置的 API 服务。<br>朗读使用 macOS 日语语音；跟读录音仅保留在本机。</div></aside></div>`;}
async function openLesson(day,generate=false,tab='grammar',regenerate=false){
 if(generate&&generatingLessons.has(day))return;
 const request=++lessonRequest;
 const same=selectedLessonNo===day;
 selectedLessonNo=day;checkpoint=null;lessonLoadError='';
 if(!same||!generate)lesson=null;
 lessonLoading=!generate;
 if(generate)generatingLessons.add(day);
 const current=()=>selectedLessonNo===day&&(generate||request===lessonRequest);
 await navigate('lessons');
 await run(generate?'Haru 正在为你准备课程…':'正在读取课程…',async()=>{
  try{
   const courseCatalog=await rpc('curriculum',{stage:state.stages.find(p=>p.start<=day&&p.end>=day)?.stage||catalog.stage});
   if(current()){catalog=courseCatalog;if(page==='lessons')render();}
   const d=await rpc('lesson',{day,source:'ai',cached_only:!generate,regenerate});
   if(current()){if(generate)++lessonRequest;lesson=d;lessonLoading=false;}
   if(generate){await refresh();if(current())catalog=await rpc('curriculum',{stage:courseCatalog.stage});}
   if(current()&&page==='lessons'){render();if(lesson)setLessonTab(tab==='listening'?'speaking':tab);}
  }catch(e){
   if(current()){lessonLoading=false;if(!generate)lessonLoadError=e.message;}
   throw e;
  }finally{
   if(generate)generatingLessons.delete(day);
   if(current())lessonLoading=false;
   if(page==='lessons'){
    // Refresh selection/status without throwing away answers in an open lesson.
    const selector=$('.course-selector');if(selector){selector.outerHTML=lessonSelection();syncCourseSelection();}
    if(!lesson&&!checkpoint)$('#lesson-body').innerHTML=pendingLesson();
   }
  }
 });
}
async function continueLearning(tab='grammar'){const request=navigationRun;await refresh();if(request!==navigationRun)return;const p=state.progression;if(p.next_lesson)return openLesson(p.next_lesson,false,tab);return openCheckpoint(p.status==='review_required');}
async function openCheckpoint(remedial=false){const request=navigationRun;selectedLessonNo=null;++lessonRequest;lessonLoading=false;await run(remedial?'正在整理错题补强…':'正在准备阶段评估…',async()=>{const d=await rpc(remedial?'remedial':'stage_assessment');if(request!==navigationRun)return;if(remedial){lesson=d;checkpoint=null;}else{checkpoint=d;lesson=null;}await refresh();if(request!==navigationRun)return;catalog=state.curriculum;await navigate('lessons');});}
function setLessonTab(tab){document.querySelectorAll('[data-lesson-tab]').forEach(b=>b.classList.toggle('active',b.dataset.lessonTab===tab));if($('#lesson-tab-content')){$('#lesson-tab-content').innerHTML=lessonTab(tab);if($('#lesson-tab-content [data-reading-text]'))void noteExposure(lesson?.id);}}
async function exportData(type){await run('正在导出…',async()=>{lastExport=await rpc('export',{type});$('#modal-content').innerHTML=`<h2>已经导出学习档案</h2><p class="hint">学习档案含课程、词卡与对话记录。</p><p class="prose" style="margin:18px 0">${esc(lastExport.path)}</p><div class="form-row">${btn('打开文件位置','reveal-export','primary')}${btn('完成','close-modal')}</div>`;$('#modal').showModal();});}
async function handleAction(a,b){switch(a){case 'retry-daily-word':await loadDailyWord();break;case 'add-daily-word':if(!dailyWord||dailyWordAdded)break;await run('正在收好这张词卡…',async()=>{await rpc('daily_word_add',{id:dailyWord.id});dailyWordAdded=true;await refresh();if(page==='home')render();toast('已加入词卡，相同词条不会重复添加。');},b);break;case 'random-card':await generateCard(null,b);break;case 'open-card':selectedCard=b.dataset.id;render();break;case 'card-review':selectedCard=null;flipped=false;render();break;case 'start-lesson':await continueLearning(b?.dataset.tab||'grammar');break;case 'select-lesson':await openLesson(Number(b.dataset.day));break;case 'regenerate-lesson':await openLesson(selectedLessonNo,true,'grammar',true);break;case 'generate-lesson':await openLesson(selectedLessonNo,true);break;case 'to-speaking':setLessonTab('speaking');break;case 'to-exercise':setLessonTab('exercise');break;case 'seed-cards':await run('正在收好入门卡…',async()=>{cardList=await rpc('card_seed');await refresh();await navigate('cards');toast('五张入门卡已加入，相同词条不会重复添加。');},b);break;case 'flip':flipped=!flipped;render();break;case 'review':await run('正在安排下次复习…',async()=>{const r=await rpc('review',{id:b.dataset.id,quality:Number(b.dataset.quality)});cardList=await rpc('cards',{order:'recent'});flipped=false;await refresh();if(page==='cards')render();toast(r.interval?'下次复习：'+r.due.slice(0,10):'10分钟后再见一次。');},b);break;case 'weekly-quiz':case 'local-quiz':await run('正在根据本周记录出题…',async()=>{test=await rpc('quiz',{source:a==='local-quiz'?'builtin':'ai'});if(page==='progress')render();},b);break;case 'export-json':await exportData('json');break;case 'settings':await navigate('settings');break;case 'refresh-config':await loadAIConfig();break;case 'record':if(!haruHasNative()){toast('跟读录音请在 Haru 桌面 App 中使用。');break;}await run(record?'正在保存录音…':'正在准备麦克风…',async()=>{await rpc(record?'record_stop':'record_start');record=!record;if($('#record-btn')){$('#record-btn').innerHTML=icon(record?'stop':'mic')+(record?' 停止并保存':' 录下我的跟读');$('#record-btn').classList.toggle('recording',record);}toast(record?'正在录音，点击停止保存（最长60秒）。':'录音已保存在本机，可以回放。');},b);break;case 'play-recording':await run('准备回放…',()=>rpc('record_play'),b);break;case 'reveal-export':if(lastExport)await rpc('reveal',{path:lastExport.path}).catch(e=>toast(e.message,true));break;case 'close-modal':$('#modal').close();break;}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.nav){e.preventDefault();await navigate(b.dataset.nav);return;}if(b.matches('.brand')){e.preventDefault();await navigate('home');return;}if(b.dataset.speak){await speakText(b.dataset.speak);return;}if(b.dataset.lessonTab){setLessonTab(b.dataset.lessonTab);return;}if(b.dataset.scene){drafts.chat=$('#chat-input')?.value||drafts.chat;scene=b.dataset.scene;chatState=null;chatMessages=[];render();await loadChat();return;}if(b.dataset.example){drafts.grammar=b.dataset.example;$('#decode-input').value=drafts.grammar;return;}if(b.dataset.addWord){const word=b.dataset.addWord;await run('正在为生词制作学习卡…',async()=>{cardList=await rpc('card_create',{word});await refresh();toast('学习卡已加入词卡盒。');},b);return;}if(b.dataset.url){if(haruHasNative())await rpc('open_url',{url:b.dataset.url}).catch(e=>toast(e.message,true));else window.open(b.dataset.url,'_blank','noopener');return;}if(b.dataset.action)await handleAction(b.dataset.action,b);});
document.addEventListener('change',async e=>{if(e.target.id==='lesson-stage'){const request=++stageRequest,nav=navigationRun;const stage=Number(e.target.value);await run('正在读取阶段课程…',async()=>{const next=await rpc('curriculum',{stage});if(request!==stageRequest||nav!==navigationRun||page!=='lessons')return;catalog=next;await openLesson(next.courses[0].lesson_no);});}});
document.addEventListener('change',e=>{if(e.target.id==='random-count')randomCount=Number(e.target.value);});
document.addEventListener('input',e=>{if(e.target.id==='card-search'){cardSearch=e.target.value;$('#card-history').innerHTML=cardHistoryRows();return;}const keys={'chat-input':'chat','decode-input':'grammar','card-word':'word','immersion-topic':'topic'};if(keys[e.target.id])drafts[keys[e.target.id]]=e.target.value;});
document.addEventListener('keydown',e=>{if(e.target.id==='chat-input'&&(e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();$('#chat-form').requestSubmit();}});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target;if(f.id==='ai-config-form'){await saveAIConfig(f,e.submitter?.value==='test');return;}const b=f.querySelector('button[type="submit"],button:not([type])');if(f.id==='profile-form'){const d=new FormData(f);await run('正在保存偏好…',async()=>{await rpc('profile',{name:d.get('name'),minutes:Number(d.get('minutes')),goal:d.get('goal'),romaji:d.has('romaji')});await refresh();toast('已保存你的学习节奏。');},b);}if(f.id==='card-form'){await generateCard($('#card-word').value,b);}if(f.id==='decode-form'){const value=$('#decode-input').value;await run('正在一点点拆解句子…',async()=>{decoded=await rpc('decode',{text:value});if(page==='grammar')render();},b);}if(f.id==='immersion-form'){const topic=$('#immersion-topic').value;await run('正在写一个属于你的日语故事…',async()=>{story=await rpc('immersion',{topic});if(page==='immersion')render();},b);}if(f.id==='chat-form'){await sendChat();}if(f.id==='quiz-form'){const count=f.querySelectorAll('.quiz-question').length;const form=new FormData(f);const answers=Array.from({length:count},(_,i)=>form.has('q'+i)?Number(form.get('q'+i)):null);if(answers.includes(null)){toast('请先完成所有题目。',true);return;}await run('正在核对答案…',async()=>{const r=await rpc('grade',{id:f.dataset.id,answers});await refresh();if(f.isConnected){r.results.forEach((x,i)=>{const t=$('#feedback-'+i);if(t)t.innerHTML=`<div class="result-line ${x.correct?'':'wrong'}">${x.correct?'✓ 回答正确':'再看一眼 · 正确选项 '+String.fromCharCode(65+x.answer)} · ${esc(x.explanation)}</div>`;});$('#quiz-result').innerHTML=`<div class="score-banner"><strong>${r.score}<small> 分</small></strong><div><h3>${r.kind==='stage_assessment'?(r.passed?'阶段通过，下一阶段已解锁':'先补强，再重新评估'):r.kind==='remedial'?(r.passed?'补强完成，可以重新评估':'继续补强不熟悉的题目'):r.score>=80?'今天又前进了一步':'把不熟悉的地方，再看一遍'}</h3><p>${r.recorded?'已保存本次结果；错题会用于后续教学。':r.kind==='stage_assessment'||r.kind==='remedial'?'此份结果已记录，显示已保存成绩。':'本次为重做反馈，首次提交记录保持不变。'}</p>${r.skills?`<p>${Object.entries(r.skills).map(([k,v])=>({grammar:'语法与词汇',kana:'假名',listening:'听力'}[k])+': '+v.correct+'/'+v.total).join(' · ')}</p>`:''}${btn('继续学习 '+icon('arrow'),'start-lesson','soft')}</div></div>`;f.querySelectorAll('input,button').forEach(el=>el.disabled=true);}document.querySelectorAll('.stage-panel').forEach(el=>el.outerHTML=stagePanel());$('#nav').innerHTML=nav();},b);}});
async function speakText(text){try{if(haruHasNative()){await rpc('speak',{text,rate:0.42});}else if('speechSynthesis' in window){const voices=speechSynthesis.getVoices();const v=voices.find(x=>x.lang.startsWith('ja'));if(!v){toast('未找到日语语音，请使用 Haru 桌面 App 或安装系统日语语音。',true);return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.voice=v;u.rate=.8;speechSynthesis.speak(u);}else toast('当前环境不支持朗读，请使用 Haru 桌面 App。',true);}catch(e){toast(e.message,true);}}
window.haruRecordingStopped=()=>{record=false;if($('#record-btn')){$('#record-btn').innerHTML=icon('mic')+' 录下我的跟读';$('#record-btn').classList.remove('recording');}toast('录音已保存（最长60秒）。');};
$('#settings-nav').innerHTML=icon('settings')+'偏好设置';
(async()=>{try{await refresh();await navigate('home');void loadDailyWord();}catch(e){$('#main').innerHTML=empty('暂时没有打开学习空间',esc(e.message),'<p class="hint">请通过 start.command（macOS）或 start.cmd（Windows）启动。</p>');}})();
